# fly.toml app configuration file generated for atproto-link-aggregator on 2024-11-15T12:13:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atproto-link-aggregator'
primary_region = 'yyz'

[build]

[mounts]
  source = "atproto_links"
  destination = "/data"
  initial_size = "10gb"

[env]
  DB_PATH = "/data/links.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
